name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        dotnet-runtime: [win-x64]
    runs-on: windows-latest
    env:
      dotnetActionVersion: '10.0.x'
      dotnetBuildVersion: 'net10.0'
      frameworkVersion: net10.0-windows10.0.22621.0
      desktopFolderName: Woohoo.ChecksumMatcher.WinUI
      desktopProjectName: Woohoo.ChecksumMatcher.WinUI.csproj
      desktopBinariesName: Woohoo.ChecksumMatcher.WinUI-${{ github.event.release.tag_name }}-${{ matrix.dotnet-runtime }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnetActionVersion }}

    - name: Desktop App - Build / Publish
      working-directory: src
      run: dotnet publish ${{ env.desktopFolderName }}/${{ env.desktopProjectName }} -f ${{ env.frameworkVersion }} -r ${{ matrix.dotnet-runtime }} -c Release --self-contained -p:DebugType=None -p:DebugSymbols=False

    - name: Desktop App - Zip binaries
      shell: pwsh
      working-directory: ${{ github.workspace }}/src/${{ env.desktopFolderName }}/bin/Release/${{ env.frameworkVersion }}/${{ matrix.dotnet-runtime }}/publish
      run: Compress-Archive -Path ./* -DestinationPath "${{ github.workspace }}/src/${{ env.desktopFolderName }}/bin/Release/${{ env.frameworkVersion }}/${{ env.desktopBinariesName }}.zip"

    - name: Desktop App - Upload binaries artifact
      uses: actions/upload-artifact@v4
      with:
        name: desktop-${{ matrix.dotnet-runtime }}
        path: src/${{ env.desktopFolderName }}/bin/Release/${{ env.frameworkVersion }}/${{ env.desktopBinariesName }}.zip

  release:
    name: Upload Release Assets
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download binaries artifacts for all runtimes
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts
        merge-multiple: true

    - name: Display downloaded artifacts
      run: ls -R release-artifacts

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release-artifacts/*
